version: '3.9'

services: 
    db:
        image: postgres
        volumes: 
            - ./partition:/home/partition
            - ./data/db:/var/lib/postgresql/data
            - ./initDB:/docker-entrypoint-initdb.d/
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - APP_DB_USER=jason
            - APP_DB_PASS=jason
            - APP_DB_NAME=covid_db
        ports: 
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 10
        stop_grace_period: 60s
    
#    pgadmin:
#        image: dpage/pgadmin4
#        environment: 
#            - PGADMIN_DEFAULT_EMAIL=jasonpinelo@gmail.com
#            - PGADMIN_DEFAULT_PASSWORD=admin
#        ports:
#            - "5050:80"
#        depends_on:
#            db:
#                condition: service_healthy

